<?php

include_once(HX_TEMPLATES . '/elementor-templates.php');
include_once(HX_PLUGIN_PATH . '/functions/functions-email.php');

use TemplatesHX\Elementor_Template_Handler as TemplateHandler;

function process_activation($success = null)
{
    global $wpdb;
    echo loader();
    sleep(2);
    $success = true;

    $user = get_users(array(
        'meta_key' => 'verification_id',
        'meta_value' => get_query_var('token_activation')
    ));
    if (count($user) > 0) {
        $token_expiration = get_user_meta($user[0]->ID, 'activation_token_expiration', true);
        $user_id = $user[0]->ID;

        if (strtotime($token_expiration) < current_time('timestamp')) {
            hide_loader_script();
            get_header();
            echo render_view_fail();
            get_footer();
            process_email_token();
        } elseif ($success === true) {
            $timestamp = time();
            $random_string = wp_generate_password(32, false);
            $user_activation_key = $timestamp . ':$P' . $random_string;

            $query = $wpdb->prepare(
                "UPDATE {$wpdb->prefix}users SET user_activation_key = %s WHERE ID = %d",
                $user_activation_key,
                $user_id
            );
            $wpdb->query($query);

            update_user_meta($user_id, 'is_email_verified', 1);
            hide_loader_script();
            $content = render_view_success($user);
            get_header();
            echo $content;
            get_footer();

            return true;
        }
    } else {
        hide_loader_script();
        get_header();
        echo render_view_fail();
        get_footer();
        process_email_token();
    }
}
function hide_loader_script()
{
    echo "<script>setTimeout(()=>document.querySelectorAll('.wrapper')[0].remove(),2000)</script>";
}
function render_view_success($user)
{
    hide_loader_script();

    $Elementor_Template = TemplateHandler::renderTemplate('verified_user');
    $Elementor_Template = str_replace('{username}', $user[0]->user_login, $Elementor_Template);
    return $Elementor_Template;
}
function render_view_fail()
{
    hide_loader_script();
    $Elementor_Template = TemplateHandler::renderTemplate('verified_fail');
    return $Elementor_Template;
}

function process_email_token()
{
    if (isset($_POST['email_token'])) {
        $emailToken = sanitize_email($_POST['email_token']);
        $user = get_user_by('email', $emailToken);
        $user_id = $user->ID;
        if (!$user) {
            echo "<script>alert('error',The email {$emailToken} not found)</script>";
        } else {
            hx_wp_new_user_notification($user_id, '', '', 'onlytoken');
        }
    }
}
