<html lang="en" class="">

<head>

    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>Congratulations for new user</title>
    <meta name="description" content="new user email template">
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #272727;" leftmargin="0">
    <table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#272727" style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
        <tbody>
            <tr>
                <td>
                    <table style="background-color: #272727; max-width:670px; margin:0 auto;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td style="height:80px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    <a href="{site_url}" title="logo" target="_blank">
                                        <img width="280" src="https://wanderloop.com.co/wp-content/uploads/2023/08/Frame.png" title="logo" alt="logo">
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:20px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>
                                    <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0" style="max-width:670px; background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                                        <tbody>
                                            <tr>
                                                <td style="height:40px;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                                <td style="padding:0 35px;">
                                                    <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">
                                                        Get started
                                                    </h1>
                                                    <p style="font-size:15px; color:#455056; margin:8px 0 0; line-height:24px;">
                                                        Your account has been created on the {site_name}. Below is the link for your verification.</p>
                                                    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 22px;">
                                                        <tbody>
                                                            <tr>
                                                                <td style="width:50%;text-align: center;color:#455056;font-size:18px;line-height:20px;margin: 0 0 12px 0;font-weight:500">
                                                                    <span>
                                                                        <strong style="display:block;font-size:13px;margin:0 0 4px;color:rgba(0,0,0,0.64);font-weight:normal">Username</strong>
                                                                        nemotech_traveler
                                                                    </span>
                                                                </td>
                                                                <td style="width:50%;text-align: center;color:#455056;font-size:18px;line-height:20px;margin:0 0 12px 0;font-weight:500">
                                                                    <span>
                                                                        <strong style="display:block;font-size:13px;margin:0 0 4px;color:rgba(0,0,0,0.64);font-weight:normal">Token Expiration</strong>{token_expiration}</span>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <a class="button" href="{user_verification_link}" style="background:#00DA8E;text-decoration:none !important; display:inline-block; font-weight:500; margin-top:24px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Verify account</a>
                                                </td>
                                            </tr>
                                            <?php if (!empty($socials) or !empty($email_footer)) : ?>
                                                <tr>
                                                    <td>
                                                        <div style="text-align:center;color:white;margin:0 auto;padding: 15px;width: 95.2%;background-color:#00da8e;height:100%;border-bottom-left-radius:5px;border-bottom-right-radius:5px;margin-top: 40px;">
                                                            <? if ($email_footer) : ?>
                                                                <?= $email_footer ?>
                                                            <?php endif; ?>
                                                            <? if ($socials) : ?>
                                                                <div style="margin-bottom: 10px;text-align: center;font-size: 14px;padding-top: 27px;">
                                                                    <?= $socials ?>
                                                                </div>
                                                            <?php endif; ?>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:20px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    <p style="font-size:14px; color:rgb(0 218 142); line-height:18px; margin:0 0 0;">&copy; <strong>{site_url}</strong> </p>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:80px;">&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <!--/100% body table-->







</body>

</html>