<html lang="en" class="">

<head>

<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>Congratulations for new user</title>
    <meta name="description" content="new user email template">
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
    <style type="text/css">
        a.button:hover {
            background-color: #EE752C !important;
        }
    </style>



    <!-- 100% body table -->
    <table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8" style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
        <tbody>
            <tr>
                <td>
                    <table style="background-color: #f2f3f8; max-width:670px; margin:0 auto;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td style="height:80px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    <a href="{site_url}" title="logo" target="_blank">
                                        <img width="280" src="https://wanderloop.com.co/wp-content/uploads/2023/08/Frame.svg" title="logo" alt="logo">
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:20px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>
                                    <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0" style="max-width:670px; background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                                        <tbody>
                                            <tr>
                                                <td style="height:40px;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                                <td style="padding:0 35px;">
                                                    <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">
                                                        Get started
                                                    </h1>
                                                    <p style="font-size:15px; color:#455056; margin:8px 0 0; line-height:24px;">
                                                    Your account has been created on the {site_name}. Below is the link for your  verification.</p>
                                                    <span style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;"></span>
                                                    <p style="display:flex;justify-content: space-evenly;color:#455056;font-size:18px;line-height:20px;margin: 0 0 12px 0;font-weight: 500;">
                                                        <span> <strong style="display: block;font-size: 13px; margin: 0 0 4px; color:rgba(0,0,0,.64); font-weight:normal;">Username</strong>{user_name}</span>
                                                        <span><strong style="display: block;font-size: 13px;margin: 0px 0 4px 0;font-weight:normal;color:rgba(0,0,0,.64);">Token</strong>{token_user}</span>
                                                    </p>

                                                    <a class="button" href="{user_verification_link}" style="background:#00DA8E;text-decoration:none !important; display:inline-block; font-weight:500; margin-top:24px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Verify account</a>
                                                </td>
                                            </tr>
                                            <?php if (!empty($socials) or !empty($email_footer)) : ?>
                                                <tr>
                                                    <td style="height:40px;">
                                                        <div style="width: 95%;background-color: #272727;margin: 0 auto;height: 100%;">
                                                            <? if ($email_footer) : ?>
                                                                <p style="margin-top:30px;margin-bottom: 10px;text-align: center;font-size: 14px;color:#777777;padding-top: 27px;">
                                                                    <?= $email_footer ?>
                                                                </p>
                                                            <?php endif; ?>
                                                            <? if ($socials) : ?>
                                                                <p style="margin-bottom: 10px;text-align: center;font-size: 14px;color:#777777;padding-top: 27px;">
                                                                    <?= $socials ?>
                                                                </p>
                                                            <?php endif; ?>
                                                        </div>

                                                    </td>
                                                </tr>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:20px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    <p style="font-size:14px; color:rgba(69, 80, 86, 0.7411764705882353); line-height:18px; margin:0 0 0;">
                                        © <strong>{site_url}</strong> </p>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:80px;">&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <!--/100% body table-->







</body>

</html>