<?php
function renderHTML(){
    return "
    <div class='container'>
    <form name='general_register'>
        <div class='form-row'>
            <div class='form-group col-md-6'>
                <label for='name'>Name</label>
                <input type='text' class='form-control' id='name'>
            </div>
            <div class='form-group col-md-6'>
                <label for='last-name'>Last Name</label>
                <input type='text' class='form-control' id='last-name'>
            </div>
        </div>
        <div class='form-group'>
            <label>Sex</label>
            <div class='form-check'>
                <input class='form-check-input' type='checkbox' id='male'>
                <label class='form-check-label' for='male'>
                    Male
                </label>
            </div>
            <div class='form-check'>
                <input class='form-check-input' type='checkbox' id='female'>
                <label class='form-check-label' for='female'>
                    Female
                </label>
            </div>
        </div>
        <div class='form-row'>
            <div class='form-group col-md-6'>
                <label for='dob'>Date of Birth</label>
                <input type='date' class='form-control' id='dob'>
            </div>
            <div class='form-group col-md-6'>
                <label for='country'>Country of Residency</label>
                <input type='text' class='form-control' id='country'>
            </div>
        </div>
        <button type='submit' class='btn btn-primary'>Save</button>
    </form>
</div>
    ";
}